NiceAdminTheme/Controllers/BillsController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdminTheme.Models;
using System.Data.SqlClient;
using System.Data;
using OfficeOpenXml;
using System.Drawing;

namespace NiceAdminTheme.Controllers
{
    public class BillsController : Controller
    {
        #region Iconfiguration
        private IConfiguration configuration;
        public BillsController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        #endregion Iconfiguration

        #region GetBillData
        private SqlDataReader GetBillData()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Bills_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            return reader;
        }
        #endregion GetBillData

        #region SelectAllBills
        public IActionResult ListBills()
        {
            var reader = GetBillData();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
        #endregion SelectAllBills

        #region SelectBillByID
        public IActionResult BillsAddEdit(int BillID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Bills_SelectByID";
            command.Parameters.AddWithValue("@BillID", BillID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            BillsModel billModel = new BillsModel();

            foreach (DataRow dataRow in table.Rows)
            {
                billModel.BillID = Convert.ToInt32(@dataRow["BillID"]);
                billModel.BillNumber = @dataRow["BillNumber"].ToString();
                billModel.BillDate =Convert.ToDateTime( @dataRow["BillDate"]);
                billModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                billModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                billModel.Discount = Convert.ToDecimal(@dataRow["Discount"]);
                billModel.NetAmount = Convert.ToDecimal(@dataRow["NetAmount"]);
                billModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }

            OrderDropDown();
            UserDropDown();
            return View("BillsAddEdit", billModel);
            
        }
        #endregion SelectBillByID

        #region OrderDropDown
        public void OrderDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_Order_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderList.Add(orderDropDownModel);
            }            
            ViewBag.OrderList = orderList;
        }
        #endregion OrderDropDown

        #region UserDropDown
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }
            ViewBag.UserList = userList;
        }
        #endregion UserDropDown

        #region BillsSave
        public IActionResult Save(BillsModel billsmodel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("ListBills");
            }
            else
            {
                return View("BillsAddEdit", billsmodel);
            }
        }
        #endregion BillsSave

        #region BillsDelete
        public IActionResult BillsDelete(int BillID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Bills_Delete";
                command.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                command.ExecuteNonQuery();
            }
            catch (SqlException ex) when (ex.Number == 547)
            {
                TempData["ErrorMessage"] = "Unable to delete the bill as it has related records in other tables.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred: " + ex.Message;
            }
            return RedirectToAction("ListBills");
        }
        #endregion BillsDelete

        #region BillsAdd
        public IActionResult BillsSave(BillsModel billsModel)
        {
            if (billsModel.BillID  <= 0)
            {
                ModelState.AddModelError("BillID", "A valid BillID is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (billsModel.BillID == null)
                {
                    command.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    command.CommandText = "PR_Bills_Update";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = billsModel.BillID;
                }
                command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = billsModel.BillNumber;
                command.Parameters.Add("@BillDate", SqlDbType.DateTime).Value = billsModel.BillDate;
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = billsModel.OrderID;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = billsModel.TotalAmount;
                command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = billsModel.Discount;
                command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = billsModel.NetAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = billsModel.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("ListBills");
            }
            return View("BillsAddEdit", billsModel);
        }
        #endregion BillsAdd

        #region BillExportExcel
        [HttpGet]
        public async Task<IActionResult> BillExportExcel()
        {
            var reader = GetBillData();
            DataTable orderList = new DataTable();
            orderList.Load(reader);

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("userList");

                worksheet.Cells["A1"].LoadFromDataTable(orderList, true);

                int columnCount = orderList.Columns.Count;

                string rangeAddress = $"A1:{(char)('A' + columnCount - 1)}1";

                using (var range = worksheet.Cells[rangeAddress])
                {
                    range.Style.Font.Bold = true;
                    range.Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
                }

                var stream = new MemoryStream();
                await package.SaveAsAsync(stream);

                stream.Position = 0;
                var fileName = "BillList.xlsx";
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }
        #endregion BillExportExcel
    }
}

NiceAdminTheme/Views/Bills/BillsAddEdit.cshtml
@model NiceAdminTheme.Models.BillsModel
<main id="main" class="main">
    <h3>@(Model.BillID == null ? "Add" : "Update") Bill</h3>
    <form asp-action="BillsSave" method="post" class="row g-3">
        <div class="col-md-12">
            <div class="form-floating">
                <input asp-for="BillID" type="hidden" class="form-control">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-floating">
                <input type="text" asp-for="BillNumber" class="form-control" id="floatingBillNumber" placeholder="Bill Number">
                <label for="floatingBillNumber" >Bill Number</label>
                <span class="text-danger" asp-validation-for="BillNumber"></span>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-floating">
                <input type="datetime" asp-for="BillDate" class="form-control" id="floatingBillDate" placeholder="Bill Date" value="@(DateTime.Now.ToString("yyyy-MM-dd"))">
                <label for="floatingBillDate">Bill Date</label>
                <span class="text-danger" asp-validation-for="BillDate"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-floating mb-3">
                @if (ViewBag.OrderList != null)
                {
                    <select class="form-control" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID", "OrderID"))">
                        <option value="">Select OrderID</option>
                    </select>
                    <label for="floatingOrderID" asp-for="OrderID">Select OrderID</label>
                }
                <span class="text-danger" asp-validation-for="OrderID"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating">
                <input type="number" asp-for="TotalAmount" class="form-control" id="floatingTotalAmount" placeholder="Total Amount" step="0.01" min="">
                <label for="floatingTotalAmount" >Total Amount</label>
                <span class="text-danger" asp-validation-for="TotalAmount"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating">
                <input type="number" asp-for="Discount" class="form-control" id="floatingDiscount" placeholder="Discount" step="0.01" min="">
                <label for="floatingDiscount" >Discount</label>
                <span class="text-danger" asp-validation-for="Discount"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating">
                <input type="number" asp-for="NetAmount" class="form-control" id="floatingNetAmount" placeholder="Net Amount" step="0.01" min="">
                <label for="floatingNetAmount" >Net Amount</label>
                <span class="text-danger" asp-validation-for="NetAmount"></span>
            </div>
        </div>
       <div class="col-md-4">
            <div class="form-floating mb-3">
                @if (ViewBag.UserList != null)
                {
                    <select class="form-control" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                        <option value="">Select User</option>
                    </select>
                    <label for="floatingUserID" asp-for="UserID">Select User</label>
                }
                <span class="text-danger" asp-validation-for="UserID"></span>
            </div>
        </div> 
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="button" class="btn btn-danger">
                <a asp-action="ListBills" asp-controller="Bills" style="color: white; text-decoration: none;">
                    Back
                </a>
            </button>
        </div>
    </form>
</main>

NiceAdminTheme/Views/Bills/ListBills.cshtml
@using System.Data;
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Bill List</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Data</li>
            </ol>
            <button class="btn btn-outline-primary"><a asp-action="BillsAddEdit" asp-controller="Bills" class="nav-link">Add Bills</a></button>
            <button class="btn btn-primary"><a asp-action="BillExportExcel" asp-controller="Bills" class="nav-link">Export Bills</a></button>
        </nav>
    </div>
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="bi bi-exclamation-octagon me-1"></i>
            <span>@TempData["ErrorMessage"]</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    }
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <table class="table datatable table table-striped table-bordered table-hover table-responsive">
                            <thead>
                                <tr>
                                    <th>BillID</th>
                                    <th>BillNumber</th>
                                    <th>BillDate</th>
                                    <th>OrderID</th>
                                    <th>TotalAmount</th>
                                    <th>Discount</th>
                                    <th>NetAmount</th>
                                    <th>UserName</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (DataRow data in Model.Rows)
                                {
                                    <tr>
                                        <td class="text-center">@data["BillID"]</td>
                                        <td>@data["BillNumber"]</td>
                                        <td>@data["BillDate"]</td>
                                        <td class="text-center">@data["OrderID"]</td>
                                        <td class="text-end">$@data["TotalAmount"]</td>
                                        <td class="text-end">$@data["Discount"]</td>
                                        <td class="text-end">$@data["NetAmount"]</td>
                                        <td class="text-end">@data["UserName"]</td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <button type="button" class="btn btn-link p-0 mx-3" title="Delete" onclick="confirmDelete('@data["BillID"]')">
                                                    <i class="fas fa-trash text-danger"></i>
                                                </button>
                                                <a asp-action="BillsAddEdit" asp-controller="Bills" asp-route-BillID="@data["BillID"]" class="btn btn-link p-0" title="Edit">
                                                    <i class="fas fa-edit text-warning"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>
<script>
    function confirmDelete(billID) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = '@Url.Action("BillsDelete", "Bills")' + '?BillID=' + billID;
            }
        })
    }
</script>