NiceAdminTheme/Controllers/CityController.cs
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using NiceAdminTheme.Models;

namespace NiceAdminTheme.Controllers;

public class CityController : Controller
{
    private IConfiguration config;

    public CityController(IConfiguration config)
    {
        this.config = config;
    }

    #region Connection

    public SqlCommand Connection()
    {
        SqlConnection cons = new SqlConnection(this.config.GetConnectionString("ConnectionString"));
        cons.Open();
        SqlCommand cmd = cons.CreateCommand();
        cmd.CommandType = CommandType.StoredProcedure;
        return cmd;
    }
    #endregion

    #region SelectAll

    public IActionResult CityList()
    {
        SqlCommand cmd = Connection();
        cmd.CommandText = "PR_City_SelectAll";
        SqlDataReader reader = cmd.ExecuteReader();
        DataTable dt = new DataTable();
        dt.Load(reader);
        return View(dt);
    }
    #endregion

    #region SelectByID

    public IActionResult CityAddEdit(int? CityID)
    {
        SqlCommand cmd = Connection();
        CityModel cm = new CityModel();
        
        if (CityID.HasValue)
        {
            cmd.CommandText = "PR_City_SelectByID";
            cmd.Parameters.AddWithValue("CityID", CityID);
            SqlDataReader reader = cmd.ExecuteReader();

            if (reader.Read())
            {
                cm.CityID = reader.GetInt32("CityID");
                cm.CityName = reader.GetString("CityName");
                cm.Pincode = reader.GetString("Pincode");
                cm.StateID = reader.GetInt32("StateID");
                cm.UserID = reader.GetInt32("UserID");
            }
        }
        StateDropdown();
        UserDropdown();
        return View(cm);
    }
    #endregion

    #region Delete

    public IActionResult DeleteCity(int CityID)
    {
        try
        {
            SqlCommand cmd = Connection();
            cmd.CommandText = "PR_City_Delete";
            cmd.Parameters.AddWithValue("CityID", CityID);
            cmd.ExecuteNonQuery();
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = ex.Message;
        }
        return RedirectToAction("CityList");
    }
    #endregion

    #region Insert/Update

    public IActionResult CitySave(CityModel model)
    {
        SqlCommand cmd = Connection();
        if (ModelState.IsValid)
        {
            if (model.CityID.HasValue)
            {
                cmd.CommandText = "PR_City_Update";
                cmd.Parameters.AddWithValue("CityID", model.CityID);
            }
            else
            {
                cmd.CommandText = "PR_City_Insert";
            }

            cmd.Parameters.AddWithValue("CityName", model.CityName);
            cmd.Parameters.AddWithValue("Pincode", model.Pincode);
            cmd.Parameters.AddWithValue("StateID", model.StateID);
            cmd.Parameters.AddWithValue("UserID", model.UserID);
            cmd.ExecuteNonQuery();
        }

        return RedirectToAction("CityList");
    }
    #endregion

    #region StateDropdown

    public void StateDropdown()
    {
        SqlCommand cmd = Connection();
        cmd.CommandText = "PR_State_Dropdown";
        SqlDataReader reader = cmd.ExecuteReader();
        DataTable dt = new DataTable();
        dt.Load(reader);
        List<StateDropdownModel> sm = new List<StateDropdownModel>();

        foreach (DataRow s in dt.Rows)
        {
            StateDropdownModel model = new StateDropdownModel();
            model.StateID = Convert.ToInt32(s["StateID"]);
            model.StateName = s["StateName"].ToString();
            sm.Add(model);
        }

        ViewBag.StateList = sm;
    }
    #endregion

    #region UserDropdown

    public void UserDropdown()
    {
        SqlCommand cmd = Connection();
        cmd.CommandText = "PR_User_DropDown";
        SqlDataReader reader = cmd.ExecuteReader();
        DataTable dt = new DataTable();
        dt.Load(reader);
        List<UserDropDownModel> sm = new List<UserDropDownModel>();

        foreach (DataRow s in dt.Rows)
        {
            UserDropDownModel model = new UserDropDownModel();
            model.UserID = Convert.ToInt32(s["UserID"]);
            model.UserName = s["UserName"].ToString();
            sm.Add(model);
        }

        ViewBag.UserList = sm;
    }
    #endregion
}

NiceAdminTheme/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdminTheme.Models;
using System.Data.SqlClient;
using System.Data;
using OfficeOpenXml;

namespace NiceAdminTheme.Controllers
{
    public class UserController : Controller
    {
        #region Iconfiguration
        private IConfiguration configuration;
        public UserController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        #endregion Iconfigration

        #region GetUserData
        private SqlDataReader GetUserData()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_User_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            return reader;
        }
        #endregion GetUserData

        #region SelectAllUser
        public IActionResult UserList()
        {
            var reader = GetUserData();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
        #endregion SelectAllUser

        #region UserAddEdit
        public IActionResult UserAddEdit(int UserID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            #region UserByID

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_User_SelectByID";
            command.Parameters.AddWithValue("@UserID", UserID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            UserModel userModel = new UserModel();

            foreach (DataRow dataRow in table.Rows)
            {
                userModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
                userModel.UserName = @dataRow["UserName"].ToString();
                userModel.Email = @dataRow["Email"].ToString();
                userModel.Password = @dataRow["Password"].ToString();
                userModel.MobileNo = @dataRow["MobileNo"].ToString();
                userModel.Address = @dataRow["Address"].ToString();
                userModel.IsActive = (Boolean)Convert.ToBoolean(dataRow["IsActive"]);
            }

            #endregion

            return View("UserAddEdit", userModel);
        }
        #endregion UserAddEdit

        #region UserSave
        public IActionResult Save(UserModel usermodel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("UserList");
            }
            else
            {
                return View("UserAddEdit", usermodel);
            }
        }
        #endregion UserSave

        #region UserDelete
        public IActionResult UserDelete(int UserID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_User_Delete";
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = UserID;
                command.ExecuteNonQuery();
            }
            catch (SqlException ex) when (ex.Number == 547)
            {
                TempData["ErrorMessage"] = "Unable to delete the user as it has related records in other tables.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred: " + ex.Message;
            }
            return RedirectToAction("UserList");
        }
        #endregion UserDelete

        #region UserAdd
        public IActionResult UserSave(UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (userModel.UserID == null)
                {
                    command.CommandText = "PR_User_Insert";
                }
                else
                {
                    command.CommandText = "PR_User_Update";
                    command.Parameters.Add("@UserID", SqlDbType.Int).Value = userModel.UserID;
                }
                command.Parameters.Add("@UserName", SqlDbType.VarChar).Value = userModel.UserName;
                command.Parameters.Add("@Email", SqlDbType.VarChar).Value = userModel.Email;
                command.Parameters.Add("@Password", SqlDbType.VarChar).Value = userModel.Password;
                command.Parameters.Add("@MobileNo", SqlDbType.VarChar).Value = userModel.MobileNo;
                command.Parameters.Add("@Address", SqlDbType.VarChar).Value = userModel.Address;
                command.Parameters.Add("@IsActive", SqlDbType.Bit).Value = userModel.IsActive;
                command.ExecuteNonQuery();
                return RedirectToAction("Login");
            }

            return View("UserAddEdit", userModel);
        }
        #endregion UserAdd

        #region UserExportExcel
        [HttpGet]
        public async Task<IActionResult> UserExportExcel()
        {
            var reader = GetUserData();
            DataTable userList = new DataTable();
            userList.Load(reader);

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("userList");

                worksheet.Cells["A1"].LoadFromDataTable(userList, true);

                int columnCount = userList.Columns.Count;

                string rangeAddress = $"A1:{(char)('A' + columnCount - 1)}1";

                using (var range = worksheet.Cells[rangeAddress])
                {
                    range.Style.Font.Bold = true;
                    range.Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
                }

                var stream = new MemoryStream();
                await package.SaveAsAsync(stream);

                stream.Position = 0;
                var fileName = "UserList.xlsx";
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }
        #endregion UserExportExcel
    }
}

NiceAdminTheme/Views/Shared/_Footer.cshtml
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Coffee Shop</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">Krishirajsinh vansia</a>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

NiceAdminTheme/Views/Shared/_Header.cshtml
@{
    string UserName = Context.Session.GetString("UserName");
}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
            <img src="~/~/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">CoffeeShop</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
            <input type="text" name="query" placeholder="Search" title="Enter search keyword">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-x-circle text-danger"></i>
                        <div>
                            <h4>Atque rerum nesciunt</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>1 hr. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-check-circle text-success"></i>
                        <div>
                            <h4>Sit rerum fuga</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>2 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-info-circle text-primary"></i>
                        <div>
                            <h4>Dicta reprehenderit</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>4 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">3</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        You have 3 new messages
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-1.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-2.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Anna Nelson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>6 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-3.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>David Muldon</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>8 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="dropdown-footer">
                        <a href="#">Show all messages</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">@UserName</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>@UserName</h6>
                        <span>Web Designer</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" asp-controller="Profile" asp-action="Profile">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                            <i class="bi bi-question-circle"></i>
                            <span>Need Help?</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" asp-controller="Pages" asp-action="SignOut">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

NiceAdminTheme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - Coffee Shop</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    //--------------------------------------------------------------------------------------------------
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    //--------------------------------------------------------------------------------------------------
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">



    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
            <partial name="_Header"></partial>
            <partial name="_Sidebar"></partial>
            @RenderBody()
            <partial name="_Footer"></partial>


    
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="/vendor/php-email-form/validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Template Main JS File -->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/assets/js/main.js"></script>
</body>
</html>

NiceAdminTheme/Views/Shared/_Sidebar.cshtml
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <!-- Dashboard Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Home" asp-action="Index">
                <i class="bi bi-grid me-2 text me-2"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Product Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Product" asp-action="ProductList">
                <i class="bi bi-box-seam-fill me-2"></i>
                <span>Product</span>
            </a>
        </li>

        <!-- Users Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="User" asp-action="UserList">
                <i class="bi bi-person-fill me-2"></i>
                <span>Users</span>
            </a>
        </li>

        <!-- Orders Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Order" asp-action="OrderList">
                <i class="bi bi-cart-fill me-2"></i>
                <span>Orders</span>
            </a>
        </li>

        <!-- Order Detail Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="OrderDetail" asp-action="ListOrderDetail">
                <i class="bi bi-list-task me-2"></i>
                <span>Order Detail</span>
            </a>
        </li>

        <!-- Bills Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Bills" asp-action="ListBills">
                <i class="bi bi-file-earmark-text-fill me-2"></i>
                <span>Bills Detail</span>
            </a>
        </li>

        <!-- Customers Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Customer" asp-action="CustomerList">
                <i class="bi bi-person-lines-fill me-2"></i>
                <span>Customers Detail</span>
            </a>
        </li>

        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Project" asp-action="ListProjects">
                <i class="bi bi-cart-fill me-2"></i>
                <span>Project Detail</span>
            </a>
        </li>

        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Country" asp-action="CountryList">
                <i class="bi bi-cart-fill me-2"></i>
                <span>Country Detail</span>
            </a>
        </li>

        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="State" asp-action="StateList">
                <i class="bi bi-cart-fill me-2"></i>
                <span>State Detail</span>
            </a>
        </li>

        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="City" asp-action="CityList">
                <i class="bi bi-cart-fill me-2"></i>
                <span>City Detail</span>
            </a>
        </li>

        <!-- Register Link -->
        <li class="nav-item mb-2">
            <a class="nav-link" asp-controller="Pages" asp-action="Register">
                <i class="bi bi-person-plus-fill me-2"></i>
                <span>Register</span>
            </a>
        </li>
    </ul>
</aside>